#!/bin/bash

echo "📋 Supabase Migration Application Guide"
echo "========================================"
echo ""
echo "Option 1: Apply via Supabase Dashboard (EASIEST)"
echo "-------------------------------------------------"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Navigate to: SQL Editor"
echo "4. Click: New Query"
echo "5. Copy the entire contents of: supabase/migrations/20250110000000_create_jobs_tables.sql"
echo "6. Paste into the SQL Editor"
echo "7. Click: Run"
echo ""
echo "Option 2: Apply via Supabase CLI"
echo "---------------------------------"
echo "If you have your project credentials, run:"
echo ""
echo "  supabase db push --db-url 'postgresql://postgres:[PASSWORD]@db.[PROJECT_REF].supabase.co:5432/postgres'"
echo ""
echo "Replace:"
echo "  [PASSWORD] with your database password"
echo "  [PROJECT_REF] with your project reference ID"
echo ""
echo "Option 3: Link Project and Push"
echo "--------------------------------"
echo "1. Get your project ref from Supabase dashboard (Settings > General)"
echo "2. Run: supabase link --project-ref YOUR_PROJECT_REF"
echo "3. Run: supabase db push"
echo ""
echo "📄 Migration file location: supabase/migrations/20250110000000_create_jobs_tables.sql"
echo ""
