# Netlify Configuration for JobAI Search (Next.js)
# Enables Puppeteer with serverless-compatible Chrome

[build]
  command = "npm run build"
  publish = ".next"

[functions]
  # Use esbuild for faster builds
  node_bundler = "esbuild"

  # Exclude large packages from bundling
  # @sparticuz/chromium downloads Chrome dynamically at runtime
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]
